src/Entity/Application.php
<?php

namespace DeployTracker\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DeployTracker\Entity\Deployment;

/**
 * @ORM\Table(name="application")
 * @ORM\Entity()
 * @ORM\Entity(repositoryClass="DeployTracker\Repository\ApplicationRepository")
 */
class Application
{
    /**
     * @ORM\Column(name="id", type="integer", length=10)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(name="name", type="string", length=255, unique=true)
     *
     * @var string
     */
    private $name;

    /**
     * @ORM\Column(name="project_url", type="string", length=255)
     *
     * @var string
     */
    private $projectUrl;

    /**
     * @ORM\OneToMany(targetEntity="DeployTracker\Entity\Deployment", mappedBy="application", cascade={"remove"})
     *
     * @var Collection
     */
    private $deployments;

    public function __construct()
    {
        $this->deployments = new ArrayCollection();
    }

    /**
     * @param int $id
     * @return self
     */
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return ?int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param string $name
     * @return self
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return ?string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $projectUrl
     * @return self
     */
    public function setProjectUrl(string $projectUrl): self
    {
        $this->projectUrl = $projectUrl;

        return $this;
    }

    /**
     * @return ?string
     */
    public function getProjectUrl(): ?string
    {
        return $this->projectUrl;
    }

    /**
     * @param Collection $deployments
     * @return self
     */
    public function setDeployments(Collection $deployments): self
    {
        $this->deployments = $deployments;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getDeployments(): Collection
    {
        return $this->deployments;
    }

    /**
     * @return Collection
     */
    public function getDeploymentsByStatus(string $status): Collection
    {
        return $this->deployments->filter(function (Deployment $deployment) use ($status) {
            return $deployment->getStatus() === $status;
        });
    }

    /**
     * @return Collection
     */
    public function getSuccessfulDeployments(): Collection
    {
        return $this->getDeploymentsByStatus(Deployment::STATUS_SUCCESS);
    }

    /**
     * @return Collection
     */
    public function getFailedDeployments(): Collection
    {
        return $this->getDeploymentsByStatus(Deployment::STATUS_FAILED);
    }

    /**
     * @return Collection
     */
    public function getRollbacks(): Collection
    {
        return $this->getDeploymentsByStatus(Deployment::STATUS_ROLLBACK);
    }

    /**
     * @return ?Deployment
     */
    public function getLastDeployment(): ?Deployment
    {
        if (false === ($deployment = $this->deployments->last())) {
            return null;
        }

        return $deployment;
    }
}

src/Entity/Deployment.php
<?php

namespace DeployTracker\Entity;

use DeployTracker\Entity\Application;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="deployment")
 * @ORM\Entity()
 * @ORM\Entity(repositoryClass="DeployTracker\Repository\DeploymentRepository")
 */
class Deployment
{
    const STATUS_SUCCESS = 'success';
    const STATUS_FAILED = 'failed';
    const STATUS_ROLLBACK = 'rollback';

    /**
     * @ORM\Column(name="id", type="integer", length=10)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(name="stage", type="string", length=255)
     *
     * @var string
     */
    private $stage;

    /**
     * @ORM\Column(name="branch", type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $branch;

    /**
     * @ORM\Column(name="commit_hash", type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $commitHash;

    /**
     * @ORM\Column(name="deployer", type="string", length=255)
     *
     * @var string
     */
    private $deployer;

    /**
     * @ORM\Column(name="deploy_date", type="datetime")
     *
     * @var \DateTime
     */
    private $deployDate;

    /**
     * @ORM\ManyToOne(targetEntity="DeployTracker\Entity\Application", inversedBy="deployments", fetch="EAGER")
     * @ORM\JoinColumn(name="application_id", referencedColumnName="id")
     *
     * @var Application
     */
    private $application;

    /**
     * @ORM\Column(name="status", type="string", length=32)
     *
     * @var string
     */
    private $status;

    /**
     * @param int $id
     * @return self
     */
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return ?int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param string $stage
     * @return self
     */
    public function setStage(string $stage): self
    {
        $this->stage = $stage;

        return $this;
    }

    /**
     * @return ?string
     */
    public function getStage(): ?string
    {
        return $this->stage;
    }

    /**
     * @param ?string $branch
     * @return self
     */
    public function setBranch(?string $branch): self
    {
        $this->branch = $branch;

        return $this;
    }

    /**
     * @return ?string
     */
    public function getBranch(): ?string
    {
        return $this->branch;
    }

    /**
     * @param ?string $commitHash
     * @return self
     */
    public function setCommitHash(?string $commitHash): self
    {
        $this->commitHash = $commitHash;

        return $this;
    }

    /**
     * @return ?string
     */
    public function getCommitHash(): ?string
    {
        return $this->commitHash;
    }

    /**
     * @param string $deployer
     * @return self
     */
    public function setDeployer(string $deployer): self
    {
        $this->deployer = $deployer;

        return $this;
    }

    /**
     * @return ?string
     */
    public function getDeployer(): ?string
    {
        return $this->deployer;
    }

    /**
     * @param \DateTime $deployDate
     * @return self
     */
    public function setDeployDate(\DateTime $deployDate): self
    {
        $this->deployDate = $deployDate;

        return $this;
    }

    /**
     * @return ?\DateTime
     */
    public function getDeployDate(): ?\DateTime
    {
        return $this->deployDate;
    }

    /**
     * @param Application $application
     * @return self
     */
    public function setApplication(Application $application): self
    {
        $this->application = $application;

        return $this;
    }

    /**
     * @return ?Application
     */
    public function getApplication(): ?Application
    {
        return $this->application;
    }

    /**
     * @param string $status
     * @return self
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return ?string
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @return ?string
     */
    public function getBranchUrl(): ?string
    {
        if (null === $this->branch || null === $this->application) {
            return null;
        }

        return sprintf('%s/tree/%s', $this->application->getProjectUrl(), $this->branch);
    }

    /**
     * @return string
     */
    public function getCommitUrl(): ?string
    {
        if (null === $this->commitHash || null === $this->application) {
            return null;
        }

        return sprintf('%s/commit/%s', $this->application->getProjectUrl(), $this->commitHash);
    }

    /**
     * @return bool
     */
    public function isSuccess(): bool
    {
        return $this->status === self::STATUS_SUCCESS;
    }

    /**
     * @return bool
     */
    public function isRollback(): bool
    {
        return $this->status === self::STATUS_ROLLBACK;
    }

    /**
     * @return bool
     */
    public function isFailed(): bool
    {
        return $this->status === self::STATUS_FAILED;
    }

    /**
     * @return bool
     */
    public function hasUnknownStatus(): bool
    {
        return ($this->status !== self::STATUS_SUCCESS
            && $this->status !== self::STATUS_ROLLBACK
            && $this->status !== self::STATUS_FAILED);
    }

    /**
     * @return self
     */
    public function markAsSuccess(): self
    {
        $this->setStatus(self::STATUS_SUCCESS);

        return $this;
    }

    /**
     * @return self
     */
    public function markAsRollback(): self
    {
        $this->setStatus(self::STATUS_ROLLBACK);

        return $this;
    }

    /**
     * @return self
     */
    public function markAsFailed(): self
    {
        $this->setStatus(self::STATUS_FAILED);

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace DeployTracker\Controller;

use DeployTracker\Entity\Deployment;
use DeployTracker\Histogram\DateHistogramFactory;
use DeployTracker\Manager\ApplicationManager;
use DeployTracker\Manager\DeploymentManager;
use DeployTracker\Repository\ApplicationRepository;
use DeployTracker\Repository\DeploymentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class DashboardController extends Controller
{
    /**
     * @param DeploymentRepository $repository
     * @param DateHistogramFactory $factory
     * @return Response
     */
    public function index(DeploymentRepository $repository, DateHistogramFactory $factory): Response
    {
        return $this->render('dashboard/index.html.twig', [
            'success' => $repository->findLastByStatus(Deployment::STATUS_SUCCESS),
            'failed' => $repository->findLastByStatus(Deployment::STATUS_FAILED),
            'rollback' => $repository->findLastByStatus(Deployment::STATUS_ROLLBACK),
            'stats' => $repository->aggregateDeploymentStats(),
            'topDeployers' => $repository->findTopDeployers(),
            'lastYearHistogram' => $factory->createMonthlyDeploymentHistogram(
                $repository,
                new \DateTime('-1 year'),
                new \DateTime()
            ),
            'lastWeekHistogram' => $factory->createDailyDeploymentHistogram(
                $repository,
                new \DateTime('-1 week'),
                new \DateTime()
            ),
        ]);
    }

    /**
     * @param DeploymentManager $manager
     * @return Response
     */
    public function recent(DeploymentManager $manager): Response
    {
        $result = $manager->findMostRecent();

        return $this->render('dashboard/recent.html.twig', [
            'paginator' => $result->getPaginator(),
            'filters' => $result->getFilters(),
        ]);
    }

    /**
     * @param DeploymentManager $manager
     * @return Response
     */
    public function history(DeploymentManager $manager): Response
    {
        $result = $manager->findAll();

        return $this->render('dashboard/history.html.twig', [
            'paginator' => $result->getPaginator(),
            'filters' => $result->getFilters(),
        ]);
    }

    /**
     * @param ApplicationManager $manager
     * @return Response
     */
    public function applications(ApplicationManager $manager): Response
    {
        return $this->render('dashboard/applications.html.twig', [
            'paginator' => $manager->findAll()->getPaginator(),
        ]);
    }

    /**
     * @param int $id
     * @param ApplicationRepository $repository
     * @param DeploymentManager $manager
     * @return Response
     */
    public function application(int $id, ApplicationRepository $repository, DeploymentManager $manager): Response
    {
        if (null === ($application = $repository->findOneById($id))) {
            throw new NotFoundHttpException();
        }

        $result = $manager->findByApplication($application);

        return $this->render('dashboard/application.html.twig', [
            'application' => $application,
            'paginator' => $result->getPaginator(),
            'filters' => $result->getFilters(),
        ]);
    }

    /**
     * @param Request $request
     * @param DeploymentRepository $repository
     * @return Response
     */
    public function deployers(DeploymentManager $manager): Response
    {
        return $this->render('dashboard/deployers.html.twig', [
            'paginator' => $manager->findDeployers()->getPaginator(),
        ]);
    }
}

templates/dashboard/grid/deployment.html.twig
{% if deployments.count == 0 %}
  <div class="alert alert-warning">
    No tracked deployments available in the view.
  </div>
{% else %}
  <table class="table table-striped table-responsive-md border">
    <thead class="thead-light">
      <tr>
        <th scope="col">Application</th>
        <th scope="col">Stage</th>
        <th scope="col">Branch</th>
        <th scope="col">Commit Hash</th>
        <th scope="col">Deployer</th>
        <th scope="col">Status</th>
        <th scope="col" class="text-right">Time</th>
      </tr>
    </thead>
    <tbody>
      {% for deployment in deployments %}
        <tr>
          <th scope="row">
            <a class="text-dark" href="{{ path('dashboard_application', {id: deployment.application.id}) }}">
              {{ deployment.application.name }}
            </a>
          </th>
          <td>
            <a class="text-dark" href="{{ path(route_name(), route_params(filters|merge({stage: deployment.stage}))) }}">
              {{ deployment.stage }}
            </a>
          </td>
          <td>
            {% if deployment.branch %}
              <a class="badge badge-info" href="{{ deployment.branchUrl }}" target="_blank" rel="noopener noreferrer">
                {{ deployment.branch }}
              </a>
            {% else %}
              -
            {% endif %}
          </td>
          <td>
            {% if deployment.commitHash %}
              <a class="text-dark" href="{{ deployment.commitUrl }}" target="_blank" rel="noopener noreferrer" title="{{ deployment.commitHash }}">
                {{ deployment.commitHash|slice(0, 12) }}
              </a>
            {% else %}
              -
            {% endif %}
          </td>
          <td>
            <a class="text-dark" href="{{ path(route_name(), route_params(filters|merge({deployer: deployment.deployer}))) }}">
              {{ deployment.deployer }}
            </a>
          </td>
          <td>
            <a href="{{ path(route_name(), route_params(filters|merge({status: deployment.status}))) }}" title="{{ deployment.status }}">
              {% if deployment.success %}
                <span class="badge badge-success">{{ deployment.status }}</span>
              {% elseif deployment.failed %}
                <span class="badge badge-danger">{{ deployment.status }}</span>
              {% elseif deployment.rollback %}
                <span class="badge badge-warning">{{ deployment.status }}</span>
              {% else %}
                <span class="badge badge-secondary">unknown</span>
              {% endif %}
            </a>
          </td>
          <td class="text-right">
            <span title="{{ deployment.deployDate|date('Y-m-d H:i:s')}}">
              {{ deployment.deployDate|fuzzy_date }}
            </span>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'fragment/pagination.html.twig' %}
{% endif %}

templates/dashboard/grid/last-deployments.html.twig
{% if deployments.count == 0 %}
  <div class="alert alert-warning">
    No data available.
  </div>
{% else %}
  <table class="table table-striped table-responsive-md border">
    <thead class="thead-light">
      <tr>
        <th scope="col">Application</th>
        <th scope="col">Stage</th>
        <th scope="col" class="text-right">Time</th>
      </tr>
    </thead>
    <tbody>
      {% for deployment in deployments %}
        <tr>
          <th scope="row">
            <a class="text-dark" href="{{ path('dashboard_application', {id: deployment.application.id, status: status}) }}">
              {{ deployment.application.name }}
            </a>
          </th>
          <td>
            <a class="text-dark" href="{{ path('dashboard_history', {status: status, stage: deployment.stage}) }}">
              {{ deployment.stage }}
            </a>
          </td>
          <td class="text-right">
            <span title="{{ deployment.deployDate|date('Y-m-d H:i:s')}}">
              {{ deployment.deployDate|fuzzy_date }}
            </span>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

templates/dashboard/grid/period-stats.html.twig
<table class="table table-striped border">
  <thead class="thead-light">
    <tr>
      <th scope="col">Period</th>
      <th scope="col" class="text-right">Average</th>
      <th scope="col" class="text-right"># Last Period</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">
        Annually
      </th>
      <td class="text-right">
        {{ stats.avgPerYear|number_format(2) }}
      </td>
      <td class="text-right">
        {{ stats.lastYear|number_format }}
      </td>
    </tr>
    <tr>
      <th scope="row">
        Monthly
      </th>
      <td class="text-right">
        {{ stats.avgPerMonth|number_format(2) }}
      </td>
      <td class="text-right">
        {{ stats.lastMonth|number_format }}
      </td>
    </tr>
    <tr>
      <th scope="row">
        Weekly
      </th>
      <td class="text-right">
        {{ stats.avgPerWeek|number_format(2) }}
      </td>
      <td class="text-right">
        {{ stats.lastWeek|number_format }}
      </td>
    </tr>
    <tr>
      <th scope="row">
        Daily
      </th>
      <td class="text-right">
        {{ stats.avgPerDay|number_format(2) }}
      </td>
      <td class="text-right">
        {{ stats.last24h|number_format }}
      </td>
    </tr>
  </tbody>
</table>

templates/dashboard/grid/stats.html.twig
{% if deployments|length == 0 %}
  <div class="alert alert-warning">
    No data available.
  </div>
{% else %}
  <table class="table table-striped table-responsive-md border">
    <thead class="thead-light">
      <tr>
        <th scope="col">Application</th>
        <th scope="col">Stage</th>
        <th scope="col" class="text-right">Time</th>
      </tr>
    </thead>
    <tbody>
      {% for deployment in deployments %}
        <tr>
          <th scope="row">
            <a class="text-dark" href="{{ path('dashboard_application', {id: deployment.application.id, status: status}) }}">
              {{ deployment.application.name }}
            </a>
          </th>
          <td>
            <a class="text-dark" href="{{ path('dashboard_history', {status: status, stage: deployment.stage}) }}">
              {{ deployment.stage }}
            </a>
          </td>
          <td class="text-right">
            <span title="{{ deployment.deployDate|date('Y-m-d H:i:s')}}">
              {{ deployment.deployDate|fuzzy_date }}
            </span>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

templates/dashboard/grid/status-stats.html.twig
<table class="table table-striped border">
  <thead class="thead-light">
    <tr>
      <th scope="col">Status</th>
      <th scope="col" class="text-right">#</th>
      <th scope="col" class="text-right">Percentage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">
        <span class="badge badge-success">success</span>
      </th>
      <td class="text-right">
        {{ stats.successful|number_format }}
      </td>
      <td class="text-right">
        {{ stats.successPercentage|number_format(2) }}%
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="badge badge-warning">rollback</span>
      </th>
      <td class="text-right">
        {{ stats.rollbacks|number_format }}
      </td>
      <td class="text-right">
        {{ stats.rollbackPercentage|number_format(2) }}%
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="badge badge-danger">failed</span>
      </th>
      <td class="text-right">
        {{ stats.failed|number_format }}
      </td>
      <td class="text-right">
        {{ stats.failedPercentage|number_format(2) }}%
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="badge badge-secondary">unknown</span>
      </th>
      <td class="text-right">
        {{ stats.unknown|number_format }}
      </td>
      <td class="text-right">
        {{ stats.unknownPercentage|number_format(2) }}%
      </td>
    </tr>
  </tbody>
</table>

templates/dashboard/grid/top-deployers.html.twig
{% if deployers|length == 0 %}
  <div class="alert alert-warning">
    No tracked deployers available in the view.
  </div>
{% else %}
  <table class="table table-striped table-responsive-md border">
    <thead class="thead-light">
      <tr>
        <th scope="col">Deployer</th>
        <th scope="col" class="text-right">#</th>
        <th scope="col" class="text-right">Last</th>
      </tr>
    </thead>
    <tbody>
      {% for deployer in deployers %}
      <tr>
        <th scope="row">
          {{ deployer.name}}
        </th>
        <td class="text-right">
          {{ deployer.deploymentCount|number_format }}
        </td>
        <td class="text-right">
          {{ date(deployer.lastDeployDate)|fuzzy_date }}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}